export class COMPANY_MASTER {
    constructor(
        public CM_CODE: number,
        public CM_ID: number,
        public CM_NAME: string,
        public CM_ADDRESS1: string,
        public CM_ADDRESS2: string,
        public CM_ADDRESS3: string,
        public CM_CITY: number,
        public CM_STATE: number,
        public CM_COUNTRY: number,
        public CM_OWNER: string,
        public CM_PHONENO1: string,
        public CM_PHONENO2: string,
        public CM_PHONENO3: string,
        public CM_FAXNO: string,
        public CM_EMAILID: string,
        public CM_WEBSITE: string,
        public CM_SURCHARGE_NO: string,
        public CM_VAT_TIN_NO: string,
        public CM_CST_NO: string,
        public CM_SERVICE_TAX_NO: string,
        public CM_PAN_NO: string,
        public CM_COMMODITY_NO: string,
        public CM_ACTIVE_IND: boolean,
        public CM_OPENING_DATE: Date,
        public CM_CLOSING_DATE: Date,
        public CM_DELETE_FLAG: boolean,
        public CM_MODIFY_FLAG: boolean,
        public CM_REGD_NO: string,
        public CM_ECC_NO: string,
        public CM_VAT_WEF: Date,
        public CM_CST_WEF: Date,
        public CM_ISO_NUMBER: string,
        public CM_EXP_LICEN_NO: string,
        public CM_EXP_PERMISSOIN_NO: string,
        public CM_EXCISE_RANGE: string,
        public CM_EXCISE_DIVISION: string,
        public CM_COMMISONERATE: string,
        public CM_EXC_SUPRE_DETAILS: string,
        public CM_BANK_NAME: string,
        public CM_BANK_ADDRESS: string,
        public CM_BANK_ACC_NO: string,
        public CM_ACC_TYPE: string,
        public CM_B_SWIFT_CODE: string,
        public CM_IFSC_CODE: string,
        public CM_CIN_NO: string,
        public CM_COMM_CUSTOM: string,
        public CM_AUT_SPEC_SIGN: string,
        public CM_GST_NO: string,
    ) {

    }
}